[package]
name = "ccc-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ccc"
path = "src/main.rs"

[dependencies]
clap = { version = "4.0.18", features = ["derive"] }
ccc-core = { path = "../core" }